### ISSUE TITLE
[question] how to select column ID

### ISSUE THREAD

**Issue by machytkafitanalytics** [rtkwlf/esfdw#1]
Hi, I tested your FDW and it seems to be working great but I somehow cannot select Elasticsearch column ID. I tried different names like "id", "_id", "ID", "_ID" in foreign table but nothing - I always get NULL. But "_search" request in ES shows me "ID". Is there some special way how to query this column using your FDW? Thanks Josef

**Comment by rtkrruvinskiy** [comment]
Hi Josef,

You're right, selecting `_id` is currently broken. I'll look into getting that addressed. Thanks for reporting this!

Ray
